// DO NOT EDIT THIS FILE DIRECTLY.
// To override these values, create a `src/_user/data/collectionData.js` file
// and add your custom values there.
module.exports = [
  {
    "name": "blog",
    "displayName": "Blog",
    "description": "Latest news, articles, and updates.",
    "showInNav": true,
    "featuredImage": "/assets/images/collections/blog.jpg",
    "color": "#3498db"
  },
  {
    "name": "tutorials",
    "displayName": "Tutorials",
    "description": "Step-by-step guides to help you learn.",
    "showInNav": true,
    "featuredImage": "/assets/images/collections/tutorials.jpg",
    "hasSubmenu": true,
    "submenuCollections": ["web-development"],
    "color": "#2ecc71"
  },
  {
    "name": "web-development",
    "displayName": "Web Development",
    "description": "Tutorials focused on web development technologies.",
    "showInNav": false, 
    "featuredImage": "/assets/images/collections/web-dev.jpg",
    "color": "#f1c40f"
  }
]
