// DO NOT EDIT THIS FILE DIRECTLY.
// To override these values, create a `src/_user/data/theme.js` file
// and add your custom values there.
module.exports = {
  "colors": {
    "primary": "#333",
    "accent": "tomato",
    "background": "#fff",
    "text": "#333",
    "text-light": "#666",
    "border": "#ddd"
  },
  "fonts": {
    "body": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    "heading": "Georgia, serif"
  },
  "paths": {
    "header": "header.njk",
    "footer": "footer.njk"
  }
}
